"""Initial Alpha schema

Revision ID: 9e360b847ea5
Revises: 
Create Date: 2026-03-26 03:39:55.860187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e360b847ea5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Enum('respond_to_inquiry', 'bump_listing', 'update_listing', 'follow_up_lead', 'ship_item', 'add_tracking', 'confirm_delivery', 'request_feedback', 'review_price', 'take_photos', 'complete_checklist', 'send_chaser', 'resolve_dispute', 'manual', name='actiontype'), nullable=False),
    sa.Column('priority', sa.Enum('urgent', 'high', 'normal', 'low', name='actionpriority'), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_type', sa.Enum('item', 'lead', 'sale', 'listing', 'dispute', name='sourcetype'), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.Column('auto_generated', sa.Boolean(), nullable=True),
    sa.Column('generated_message', sa.Text(), nullable=True),
    sa.Column('generated_instructions', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actions_completed_at'), ['completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_actions_due_at'), ['due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_actions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_actions_priority'), ['priority'], unique=False)

    op.create_table('ai_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('model_type', sa.String(length=50), nullable=True),
    sa.Column('cost_tier', sa.String(length=10), nullable=True),
    sa.Column('context_length', sa.Integer(), nullable=True),
    sa.Column('supports_streaming', sa.Boolean(), nullable=True),
    sa.Column('supports_reasoning', sa.Boolean(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.Column('prompt_price', sa.Float(), nullable=True),
    sa.Column('completion_price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_models_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_models_model_id'), ['model_id'], unique=True)

    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_name'), ['name'], unique=True)

    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('contact_method', sa.String(length=50), nullable=True),
    sa.Column('contact_info', sa.String(length=255), nullable=True),
    sa.Column('interest_level', sa.Enum('hot', 'warm', 'cold', 'tire_kicker', 'unknown', name='interestlevel'), nullable=True),
    sa.Column('is_bundle_inquiry', sa.Boolean(), nullable=True),
    sa.Column('source_listing_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('new', 'in_progress', 'waiting_on_buyer', 'waiting_on_me', 'agreed', 'snoozed', 'dead', name='leadstatus'), nullable=True),
    sa.Column('offered_price', sa.String(length=50), nullable=True),
    sa.Column('transaction_type', sa.Enum('shipped', 'local', name='transactiontype'), nullable=True),
    sa.Column('agreed_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_method', sa.Enum('paypal_gs', 'paypal_ff', 'venmo', 'zelle', 'cash', 'crypto', 'other', name='paymentmethod'), nullable=True),
    sa.Column('agreed_at', sa.DateTime(), nullable=True),
    sa.Column('agreement_details', sa.JSON(), nullable=True),
    sa.Column('snooze_reason', sa.String(length=255), nullable=True),
    sa.Column('snooze_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_contact_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leads_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_username'), ['username'], unique=False)

    op.create_table('marketplaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('platform_type', sa.Enum('reddit', 'ebay', 'offerup', 'craigslist', 'swappa', 'facebook', 'other', name='platformtype'), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('fee_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fee_flat', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fee_notes', sa.Text(), nullable=True),
    sa.Column('feedback_timer_days', sa.Integer(), nullable=True),
    sa.Column('chaser_timer_days', sa.Integer(), nullable=True),
    sa.Column('bump_interval_hours', sa.Integer(), nullable=True),
    sa.Column('can_auto_bump', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('marketplaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marketplaces_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketplaces_name'), ['name'], unique=True)

    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tags_name'), ['name'], unique=True)

    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_settings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_settings_key'), ['key'], unique=True)

    op.create_table('value_factors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('multiplier', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('value_factors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_value_factors_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_value_factors_name'), ['name'], unique=True)

    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('condition', sa.Enum('new', 'like_new', 'good', 'fair', 'poor', name='itemcondition'), nullable=True),
    sa.Column('cost_basis', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('acquisition_source', sa.String(length=255), nullable=True),
    sa.Column('acquisition_condition', sa.Enum('new', 'used', name='acquisitioncondition'), nullable=True),
    sa.Column('acquisition_date', sa.Date(), nullable=True),
    sa.Column('asking_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('min_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('platform_prices', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('inventory', 'draft', 'listed', 'sold', 'archived', name='itemstatus'), nullable=True),
    sa.Column('is_bundle', sa.Boolean(), nullable=True),
    sa.Column('bundle_item_ids', sa.JSON(), nullable=True),
    sa.Column('draft_posts', sa.JSON(), nullable=True),
    sa.Column('ready_checklist', sa.JSON(), nullable=True),
    sa.Column('active_listings', sa.JSON(), nullable=True),
    sa.Column('price_history', sa.JSON(), nullable=True),
    sa.Column('total_views', sa.Integer(), nullable=True),
    sa.Column('total_responses', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('listed_at', sa.DateTime(), nullable=True),
    sa.Column('sold_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_status'), ['status'], unique=False)

    op.create_table('lead_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Enum('incoming', 'outgoing', name='messagedirection'), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('review_status', sa.Enum('needs_review', 'responded', 'ignored', 'snoozed', name='reviewstatus'), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('response_details', sa.JSON(), nullable=True),
    sa.Column('ignore_reason', sa.String(length=255), nullable=True),
    sa.Column('ignore_notes', sa.Text(), nullable=True),
    sa.Column('snooze_reason', sa.String(length=255), nullable=True),
    sa.Column('snooze_until', sa.DateTime(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lead_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lead_messages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_messages_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_messages_review_status'), ['review_status'], unique=False)

    op.create_table('marketplace_ai_prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marketplace_id', sa.Integer(), nullable=False),
    sa.Column('prompt_type', sa.Enum('title', 'body', 'price_research', 'response', name='prompttype'), nullable=False),
    sa.Column('prompt_template', sa.Text(), nullable=False),
    sa.Column('model_preference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['marketplace_id'], ['marketplaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('marketplace_ai_prompts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marketplace_ai_prompts_id'), ['id'], unique=False)

    op.create_table('marketplace_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marketplace_id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.Enum('title', 'body', 'image', 'general', name='ruletype'), nullable=False),
    sa.Column('rule_text', sa.Text(), nullable=False),
    sa.Column('is_strict', sa.Boolean(), nullable=True),
    sa.Column('example_good', sa.Text(), nullable=True),
    sa.Column('example_bad', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['marketplace_id'], ['marketplaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('marketplace_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marketplace_rules_id'), ['id'], unique=False)

    op.create_table('reddit_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('gmail_message_id', sa.String(length=255), nullable=True),
    sa.Column('from_user', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('message_type', sa.String(length=50), nullable=True),
    sa.Column('extracted_message', sa.Text(), nullable=True),
    sa.Column('email_date', sa.DateTime(), nullable=True),
    sa.Column('email_from', sa.String(length=255), nullable=True),
    sa.Column('email_subject', sa.String(length=500), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('is_replied', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reddit_messages', schema=None) as batch_op:
        batch_op.create_index('ix_reddit_messages_gmail_id', ['gmail_message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reddit_messages_gmail_message_id'), ['gmail_message_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_reddit_messages_id'), ['id'], unique=False)

    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.Enum('shipped', 'local', name='transactiontype'), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('paypal_gs', 'paypal_ff', 'venmo', 'zelle', 'cash', 'crypto', 'other', name='paymentmethod'), nullable=True),
    sa.Column('buyer_username', sa.String(length=255), nullable=False),
    sa.Column('buyer_address', sa.Text(), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('platform_fees', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_fees', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('shipping_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cost_basis', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('profit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('shipping_carrier', sa.Enum('usps', 'ups', 'fedex', 'other', name='shippingcarrier'), nullable=True),
    sa.Column('shipping_service', sa.String(length=100), nullable=True),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('tracking_url', sa.String(length=500), nullable=True),
    sa.Column('label_source', sa.String(length=50), nullable=True),
    sa.Column('package_dimensions', sa.JSON(), nullable=True),
    sa.Column('shipping_tasks', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('paid', 'shipped', 'delivered', 'complete', name='salestatus'), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('shipped_date', sa.DateTime(), nullable=True),
    sa.Column('delivered_date', sa.DateTime(), nullable=True),
    sa.Column('delivery_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('feedback_timer_days', sa.Integer(), nullable=True),
    sa.Column('feedback_requested_at', sa.DateTime(), nullable=True),
    sa.Column('completion_type', sa.Enum('with_feedback', 'no_feedback', 'local_sale', name='completiontype'), nullable=True),
    sa.Column('feedback_received', sa.Boolean(), nullable=True),
    sa.Column('feedback_type', sa.Enum('positive', 'neutral', 'negative', name='feedbacktype'), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('feedback_link', sa.String(length=500), nullable=True),
    sa.Column('feedback_given', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_status'), ['status'], unique=False)

    op.create_table('disputes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('not_as_described', 'damaged_in_shipping', 'missing_items', 'not_received', 'buyer_remorse', 'negative_feedback', 'other', name='disputetype'), nullable=False),
    sa.Column('status', sa.Enum('open', 'waiting_buyer', 'waiting_seller', 'resolved_positive', 'resolved_neutral', 'resolved_negative', 'refunded', name='disputestatus'), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('refund_details', sa.JSON(), nullable=True),
    sa.Column('communications', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('disputes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disputes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_disputes_status'), ['status'], unique=False)

    op.create_table('item_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('image_type', sa.Enum('physical', 'specs', 'performance', 'receipt', 'other', name='imagetype'), nullable=True),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_images_id'), ['id'], unique=False)

    op.create_table('item_tags',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', 'tag_id')
    )
    op.create_table('item_value_factors',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('value_factor_id', sa.Integer(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['value_factor_id'], ['value_factors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', 'value_factor_id')
    )
    op.create_table('lead_items',
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('lead_id', 'item_id')
    )
    op.create_table('message_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('purpose', sa.Enum('additional_photos', 'performance_screenshot', 'timestamp_photo', 'shipping_estimate', 'other', name='attachmentpurpose'), nullable=True),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['lead_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_attachments_id'), ['id'], unique=False)

    op.create_table('sale_items',
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sale_id', 'item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sale_items')
    with op.batch_alter_table('message_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_attachments_id'))

    op.drop_table('message_attachments')
    op.drop_table('lead_items')
    op.drop_table('item_value_factors')
    op.drop_table('item_tags')
    with op.batch_alter_table('item_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_images_id'))

    op.drop_table('item_images')
    with op.batch_alter_table('disputes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disputes_status'))
        batch_op.drop_index(batch_op.f('ix_disputes_id'))

    op.drop_table('disputes')
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_status'))
        batch_op.drop_index(batch_op.f('ix_sales_id'))

    op.drop_table('sales')
    with op.batch_alter_table('reddit_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reddit_messages_id'))
        batch_op.drop_index(batch_op.f('ix_reddit_messages_gmail_message_id'))
        batch_op.drop_index('ix_reddit_messages_gmail_id')

    op.drop_table('reddit_messages')
    with op.batch_alter_table('marketplace_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marketplace_rules_id'))

    op.drop_table('marketplace_rules')
    with op.batch_alter_table('marketplace_ai_prompts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marketplace_ai_prompts_id'))

    op.drop_table('marketplace_ai_prompts')
    with op.batch_alter_table('lead_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_messages_review_status'))
        batch_op.drop_index(batch_op.f('ix_lead_messages_lead_id'))
        batch_op.drop_index(batch_op.f('ix_lead_messages_id'))

    op.drop_table('lead_messages')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_status'))
        batch_op.drop_index(batch_op.f('ix_items_name'))
        batch_op.drop_index(batch_op.f('ix_items_id'))

    op.drop_table('items')
    with op.batch_alter_table('value_factors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_value_factors_name'))
        batch_op.drop_index(batch_op.f('ix_value_factors_id'))

    op.drop_table('value_factors')
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_settings_key'))
        batch_op.drop_index(batch_op.f('ix_user_settings_id'))

    op.drop_table('user_settings')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_name'))
        batch_op.drop_index(batch_op.f('ix_tags_id'))

    op.drop_table('tags')
    with op.batch_alter_table('marketplaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marketplaces_name'))
        batch_op.drop_index(batch_op.f('ix_marketplaces_id'))

    op.drop_table('marketplaces')
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_username'))
        batch_op.drop_index(batch_op.f('ix_leads_status'))
        batch_op.drop_index(batch_op.f('ix_leads_id'))

    op.drop_table('leads')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_name'))
        batch_op.drop_index(batch_op.f('ix_categories_id'))

    op.drop_table('categories')
    with op.batch_alter_table('ai_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_models_model_id'))
        batch_op.drop_index(batch_op.f('ix_ai_models_id'))

    op.drop_table('ai_models')
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actions_priority'))
        batch_op.drop_index(batch_op.f('ix_actions_id'))
        batch_op.drop_index(batch_op.f('ix_actions_due_at'))
        batch_op.drop_index(batch_op.f('ix_actions_completed_at'))

    op.drop_table('actions')
    # ### end Alembic commands ###
